name: Add Tag

on:
  push:
    branches:
      - feature/**

jobs:
  get-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Print Repo Name
        run: |
          echo ${{github.repository}}
        
      - name: Get Tags of Repo
        run: |
        gh api \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}" \
        /repos/${{github.repository}}/git/matching-refs/