name: Add Tag

on:
  push:
    branches:
      - feature/**

jobs:
  get-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Set up ENV
        uses: allenevans/set-env@v2.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Print Repo Name
        run: |
          echo ${{github.repository}}