name: Add Tag

on:
  push:
    branches:
      - feature/**

jobs:
  get-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Print Repo Name
        run: |
          echo ${{github.repository}}

      - name: Get Tags of Repo
        id: get-tags
        env:
          GH_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          gh api repos/${{github.repository}}/git/matching-refs/tags
          echo "::set-output name=tags::gh api repos/${{github.repository}}/git/matching-refs/tags"

      - name: Print Tags
        run: |
          echo ${{steps.get-tags.outputs.tags}}