name: Add Tag

on:
  push:
    branches:
      - feature/**

jobs:
  get-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Print Repo Name
        run: |
          echo ${{github.repository}}

      - name: Get Tags of Repo
        id: get-tags
        env:
          GH_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          tags="$(gh api repos/${{github.repository}}/git/matching-refs/tags -H 'Accept: application/vnd.github.v3+json' | jq -r '.[].ref' | sed 's/refs\/tags\///g' | sort -V | tail -n 1)"
          echo 'TAGS='$tags >> $GITHUB_ENV

      - name: Print Tags
        run: |
          echo $TAGS

      - name: Split Tag
        id: split-tag
        run: |
          IFS='.' read -ra tag <<< "$TAGS"
          echo "MAJOR=${tag[0]}" >> $GITHUB_ENV
          echo "MINOR=${tag[1]}" >> $GITHUB_ENV
          echo "PATCH=${tag[2]}" >> $GITHUB_ENV

      - name: Increment Patch
        id: increment-patch
        run: |
          echo "PATCH=$((PATCH + 1))" >> $GITHUB_ENV

      - name: Increment Minor
        id: increment-minor
        # if: ${{ github.ref == 'refs/heads/feature/**' }}
        run: |
          echo "MINOR=$((MINOR + 1))" >> $GITHUB_ENV
          echo "PATCH=0" >> $GITHUB_ENV
      
      - name: Join Major, Minor and Patch
        id: join-tag
        run: |
          echo "TAG=$MAJOR.$MINOR.$PATCH" >> $GITHUB_ENV
      
      - name: get commit sha
        id: get-sha
        run: |
          echo "SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Print SHA
        run: |
          echo $SHA
      # - name: Create Tag
      #   id: create-tag
      #   env:
      #     GH_TOKEN: ${{ secrets.MY_TOKEN }}
      #   run: |
      #     gh api repos/${{github.repository}}/git/refs -X POST -f ref=refs/tags/$TAG -f sha=$GITHUB_SHA